# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  resource_group_name: 'storagerg'
  location: 'eastus'
  storage_account_name: 'mystgihdgtrjkkgjbjkgd'

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'azure-devops'
    backendAzureRmOverrideSubscriptionID: '3fb059b8-93d4-4b42-b323-c4fe44b4b3c7'
    backendAzureRmResourceGroupName: 'Backend_RG'
    backendAzureRmStorageAccountName: 'terraformstorage568547'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAzureRM: 'azure-devops'